src/Entity/Student.php
<?php

namespace App\Entity;

use App\Repository\StudentRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use PhpParser\Node\Expr\Cast\String_;

#[ORM\Entity(repositoryClass: StudentRepository::class)]
class Student
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $name = null;

    #[ORM\Column(length: 50)]
    private ?string $surname = null;

    #[ORM\Column(length: 1)]
    private ?string $sex = null;

    #[ORM\Column(type: Types::DATE_MUTABLE)]
    private ?\DateTimeInterface $birthdate = null;

    #[ORM\Column(length: 50)]
    private ?string $town = null;

    #[ORM\Column(length: 255)]
    private ?string $mail = null;

    #[ORM\Column(length: 20)]
    private ?string $phone = null;

    /**
     * @var Collection<int, Session>
     */
    #[ORM\ManyToMany(targetEntity: Session::class, inversedBy: 'students')]
    private Collection $sessions;

    public function __construct()
    {
        $this->sessions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSurname(): ?string
    {
        return $this->surname;
    }

    public function setSurname(string $surname): static
    {
        $this->surname = $surname;

        return $this;
    }

    public function getFullName(): String
    {
        return $this->name . " " . $this->surname;
    }

    public function getSex(): ?string
    {
        return $this->sex;
    }

    public function setSex(string $sex): static
    {
        $this->sex = $sex;

        return $this;
    }

    public function getBirthdate(): ?\DateTimeInterface
    {
        return $this->birthdate;
    }

    public function setBirthdate(\DateTimeInterface $birthdate): static
    {
        $this->birthdate = $birthdate;

        return $this;
    }

    public function getAge(): ?string
    {
        $now = new \DateTime();
        $interval = $this->birthdate->diff($now);
        return $interval->format("%Y");
    }

    public function getTown(): ?string
    {
        return $this->town;
    }

    public function setTown(string $town): static
    {
        $this->town = $town;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): static
    {
        $this->mail = $mail;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    /**
     * @return Collection<int, Session>
     */
    public function getSessions(): Collection
    {
        return $this->sessions;
    }

    public function addSession(Session $session): static
    {
        if (!$this->sessions->contains($session)) {
            $this->sessions->add($session);
        }

        return $this;
    }

    public function removeSession(Session $session): static
    {
        $this->sessions->removeElement($session);

        return $this;
    }

    public function __toString(): String
    {
        return $this->name . " " . $this->surname;
    }
}

src/Form/StudentType.php
<?php

namespace App\Form;

use App\Entity\Session;
use App\Entity\Student;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

class StudentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('name', TextType::class, [
                'attr' => [
                    'class' => 'w-full px-5  py-4 text-gray-700 bg-gray-200 rounded'
                ]
            ])
            ->add('surname', TextType::class, [
                'attr' => [
                    'class' => 'w-full px-5  py-4 text-gray-700 bg-gray-200 rounded'
                ]
            ])
            ->add('sex', TextType::class, [
                'attr' => [
                    'class' => 'w-full px-5  py-4 text-gray-700 bg-gray-200 rounded'
                ]
            ])
            ->add('birthdate', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'w-full px-5  py-4 text-gray-700 bg-gray-200 rounded'
                ]
            ])
            ->add('town', TextType::class, [
                'attr' => [
                    'class' => 'w-full px-5  py-4 text-gray-700 bg-gray-200 rounded'
                ]
            ])
            ->add('mail', TextType::class, [
                'attr' => [
                    'class' => 'w-full px-5  py-4 text-gray-700 bg-gray-200 rounded'
                ]
            ])
            ->add('phone', TelType::class, [
                'attr' => [
                    'class' => 'w-full px-5  py-4 text-gray-700 bg-gray-200 rounded'
                ]
            ])
            ->add('add', SubmitType::class, [
                'attr' => [
                    'class' => 'text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800'
                ]
            ]);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Student::class,
            // enable/disable CSRF protection for this form
            'csrf_protection' => true,
            // the name of the hidden HTML field that stores the token
            'csrf_field_name' => '_token',
            // an arbitrary string used to generate the value of the token
            // using a different string for each form improves its security
            'csrf_token_id'   => 'task_item',
        ]);
    }
}

src/Controller/StudentController.php
<?php

namespace App\Controller;

use App\Entity\Student;
use App\Form\StudentType;
use App\Repository\StudentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class StudentController extends AbstractController
{
    // Affiche la liste des étudiants
    #[Route('/student', name: 'app_student')]
    public function index(StudentRepository $studentRepository): Response
    {
        // Vérifie si l'utilisateur est connecté
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }

        // Récupère la liste des étudiants ordonnée par nom
        $students = $studentRepository->findBy([], ["name" => "ASC"]);

        // Rend la vue Twig avec la liste des étudiants
        return $this->render('student/index.html.twig', [
            'students' => $students,
        ]);
    }

    // Ajoute ou modifie un étudiant
    #[Route('/student/new', name: 'new_student')]
    #[Route('/student/{id}/edit', name: 'edit_student')]
    public function new_edit(Student $student = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        // Vérifie si l'utilisateur est connecté
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }

        // Initialise un nouvel étudiant ou récupère un étudiant existant
        if (!$student) {
            $student = new Student();
        }

        // Crée un formulaire pour l'étudiant
        $form = $this->createForm(StudentType::class, $student);

        // Traite la requête du formulaire
        $form->handleRequest($request);

        // Vérifie si le formulaire est soumis et valide
        if ($form->isSubmitted() && $form->isValid()) {
            // Enregistre l'étudiant dans la base de données
            $entityManager->persist($student);
            $entityManager->flush();

            // Redirige vers la liste des étudiants
            return $this->redirectToRoute('app_student');
        }

        // Rend la vue Twig pour ajouter ou modifier un étudiant
        return $this->render('student/new.html.twig', [
            'formAddStudent' => $form,
        ]);
    }

    // Supprime un étudiant
    #[Route('/student/{id}/delete', name: 'delete_student')]
    public function delete(student $student, EntityManagerInterface $entityManager)
    {
        // Vérifie si l'utilisateur est connecté
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        
        // Supprime l'étudiant de la base de données
        $entityManager->remove($student);
        $entityManager->flush();

        // Redirige vers la liste des étudiants
        return $this->redirectToRoute('app_student');
    }

    // Affiche les détails d'un étudiant
    #[Route('/student/{id}', name: 'show_student')]
    public function show(student $student): Response
    {
        // Vérifie si l'utilisateur est connecté
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_login');
        }
        
        // Rend la vue Twig des détails de l'étudiant
        return $this->render('student/show.html.twig', [
            'student' => $student
        ]);
    }
}

templates/student/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello StudentController!{% endblock %}

{% block body %}

<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
    <main class="w-full flex-grow p-6">
        <h1 class="w-full text-3xl text-black mb-5">List of students</h1>
        <a href="{{ path('new_student') }}" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800 inline-block">Add a student</a>

        <div class="w-full overflow-x-auto grid grid-cols-2 md:grid-cols-3 gap-10 my-10">
            {% for student in students %}
            <div class="w-full max-w-sm bg-white border border-gray-200 rounded-lg shadow dark:bg-gray-800 dark:border-gray-700">
                <div class="flex justify-end px-4 pt-4">
                </div>
                <div class="flex flex-col items-center pb-10">
                    <a href="{{ path('show_student' , {'id': student.id}) }}">
                        <img class="w-24 h-24 mb-3 rounded-full shadow-lg" src="https://placehold.co/100x100" alt="Bonnie image"/>
                    </a>
                    <a href="{{ path('show_student' , {'id': student.id}) }}">
                        <h5 class="mb-1 text-xl font-medium text-gray-900 dark:text-white">{{ student }}</h5>
                    </a>
                    <span class="text-sm text-gray-500 dark:text-gray-400">{{ student.sex }}</span>
                    <span class="text-sm text-gray-500 dark:text-gray-400">{{ student.birthdate | date("d.m.Y") }} ({{ student.age }})</span>
                    <span class="text-sm text-gray-500 dark:text-gray-400">{{ student.town }}</span>
                    <span class="text-sm text-gray-500 dark:text-gray-400">{{ student.mail }}</span>
                    <span class="text-sm text-gray-500 dark:text-gray-400">{{ student.phone }}</span>
                    <div class="flex mt-4 md:mt-6">
                        <a href="{{ path('show_student' , {'id': student.id}) }}" class="inline-flex items-center px-4 py-2 text-sm font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Profile</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    </main>
</div>

{% endblock %}

templates/student/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add a student{% endblock %}

{% block body %}

<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
    <main class="w-full flex-grow p-6">
        <h1 class="w-full text-3xl text-black">Add a student</h1>
        <a href="{{ path('app_student') }}"><i class="fa-solid fa-rotate-left"></i></a>

        <div class="flex flex-wrap mb-10">
            <div class="w-full lg:w-1/2 my-6 pr-0 lg:pr-2">
                <p class="text-xl pb-6 flex items-center">
                    <i class="fas fa-list mr-3"></i> New student Form
                </p>
                <div class="leading-loose">

                    {{ form_start(formAddStudent) }}

                    <div class="flex gap-2">
                        <div class="w-full">
                            {{ form_row(formAddStudent.name) }}
                        </div>
                        <div class="w-full">
                            {{ form_row(formAddStudent.surname) }}
                        </div>
                    </div>

                    <div class="flex gap-2">
                        <div class="w-full">
                            {{ form_row(formAddStudent.sex) }}
                        </div>
                        <div class="w-full">
                            {{ form_row(formAddStudent.birthdate) }}
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm">
                            {{ form_row(formAddStudent.town) }}
                        </div>
                    </div>

                    <div class="flex gap-2">
                        <div class="w-full">
                            {{ form_row(formAddStudent.phone) }}
                        </div>
                        <div class="w-full">
                            {{ form_row(formAddStudent.mail) }}
                        </div>
                    </div>

                    <div class="mt-5">
                        {{ form_row(formAddStudent.add) }}
                    </div>

                    {{ form_end(formAddStudent) }}

                </div>
            </div>
        </div>
    </main>
</div>

{% endblock %}

templates/student/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Student Details{% endblock %}

{% block body %}

<div class="w-full h-screen overflow-x-hidden border-t flex flex-col">
    <main class="w-full flex-grow p-6">
        <div class="w-full flex">
            <h1 class="w-full text-3xl text-black mb-5">{{ student }}</h1>
            <a href="{{ path('app_session') }}"><i class="fa-solid fa-rotate-left"></i></a>
        </div>

        <div class="flex mb-5">
            <div class="mr-3 border-2 border-black">
                <img src="https://placehold.co/150x150" alt="">
            </div>
            <div>
                <p>Sex : {{ student.sex }}</p>
                <p>Birthdate : {{ student.birthdate | date("d.m.Y") }} ({{ student.age }})</p>
                <p>Town : {{ student.town }}</p>
                <p>Mail : {{ student.mail }}</p>
                <p>Phone : {{ student.phone }}</p>
            </div>
        </div>

        <h2 class="w-full text-2xl text-black mb-2">Upcoming session(s) :</h2>
        {% for session in student.sessions %}
        <p>{{ session }}</p>
        {% endfor %}

    </main>
</div>

{% endblock %}